use master;
IF DB_ID('ts_cm') IS NOT NULL
BEGIN
    ALTER DATABASE ts_cm
    SET SINGLE_USER
    WITH ROLLBACK IMMEDIATE;
    DROP DATABASE ts_cm
    CREATE DATABASE ts_cm
END
ELSE
BEGIN
    CREATE DATABASE ts_cm
END
